#!/bin/bash
# ================================================================
# sync_misp.sh — HFT SOC Lab MISP → Wazuh Sync Script
# Location on VM: ~/sync_misp.sh
# Usage: bash ~/sync_misp.sh
#
# What this does:
#   1. Fetches all malicious IPs from MISP (type: ip-src, to_ids: true)
#   2. Deduplicates the IP list (MISP events share IPs across campaigns)
#   3. Generates a complete local_rules.xml with dynamic <srcip> tags
#      in rule 100021 AND all static rules (100001-100004, 100010,
#      100030-100033)
#   4. Copies the rules file into the Wazuh manager container
#   5. Restarts Wazuh to load the new rules
#
# Run this whenever:
#   - You add new IPs to MISP events
#   - You create new MISP events with IoCs
#   - Rules appear to be missing from Wazuh dashboard
# ================================================================

MISP_URL="http://localhost:8081"
MISP_KEY="AFWxrosvWcWVF3bOwyaaJ9CZ8avCPGn2q0Eq0SXI"
WAZUH_CTR="single-node_wazuh.manager_1"
RULES_FILE="/var/ossec/etc/rules/local_rules.xml"

echo "=================================================="
echo " HFT SOC Lab — MISP → Wazuh Rule Sync"
echo "=================================================="
echo "[*] Fetching IoCs from MISP at ${MISP_URL}..."

# Fetch all ip-src attributes with to_ids=true, deduplicate
SRCIP_TAGS=$(curl -sk \
  -H "Authorization: ${MISP_KEY}" \
  -H "Accept: application/json" \
  -H "Content-Type: application/json" \
  -d '{"returnFormat":"json","type":"ip-src","to_ids":true}' \
  "${MISP_URL}/attributes/restSearch" \
| python3 -c "
import sys, json
data = json.load(sys.stdin)
seen = set()
for a in data.get('response',{}).get('Attribute',[]):
    ip = a.get('value','').strip()
    if ip and ip not in seen:
        seen.add(ip)
        print(f'    <srcip>{ip}</srcip>')
print(f'', file=sys.stderr)
print(f'[*] Total unique IPs fetched: {len(seen)}', file=sys.stderr)
")

if [ -z "$SRCIP_TAGS" ]; then
  echo "[!] No IPs returned from MISP. Check MISP_KEY and MISP_URL."
  echo "    Test manually: curl -sk -H 'Authorization: ${MISP_KEY}' ${MISP_URL}/users/view/me.json"
  exit 1
fi

IP_COUNT=$(echo "$SRCIP_TAGS" | grep -c "<srcip>")
echo "[✓] Fetched ${IP_COUNT} unique malicious IPs from MISP"
echo ""
echo "$SRCIP_TAGS"
echo ""

# Write the complete rules file with all rules + dynamic MISP IPs
cat > /tmp/local_rules.xml << EOF
<!-- ================================================================
     HFT SOC Lab — Custom Wazuh Rules
     Auto-generated by sync_misp.sh on: $(date)
     MISP source: ${MISP_URL}
     IPs synced: ${IP_COUNT} unique IPs

     RULE MAP:
       100001 — SSH Login Failed (Level 5)
       100002 — SSH Brute Force: 5+ failures/60s (Level 10)
       100003 — Unauthorized Algorithm Modification (Level 12)
       100010 — Market Data API Request — network tracking (Level 3)
       100004 — HTTP Flood / DoS: 40+ req/30s same IP (Level 14)
       100021 — MISP IP in raw network traffic — srcip match (Level 15)
       100030 — MISP IOC Detected — CEF event from app.log (Level 12)
       100031 — MISP CRITICAL severity — C2/Ransomware IP (Level 15)
       100032 — SOAR Auto-Block — new IP blocked (Level 13)
       100033 — Blocked IP Repeat Attempt (Level 10)
     ================================================================ -->

<group name="custom_trading_logs, hft_platform,">

  <!-- SSH Login Failed - single failure -->
  <rule id="100001" level="5">
    <if_sid>5716</if_sid>
    <description>SSH Login Failed Detected</description>
  </rule>

  <!-- SSH Brute Force - 5+ failures from same IP in 60s -->
  <rule id="100002" level="10" frequency="5" timeframe="60">
    <if_matched_sid>100001</if_matched_sid>
    <same_source_ip />
    <description>SSH Brute Force Attack Detected against HFT system</description>
  </rule>

  <!-- Unauthorized Algorithm Modification -->
  <rule id="100003" level="12">
    <decoded_as>hft_app_decoder</decoded_as>
    <match>Unauthorized</match>
    <description>CRITICAL: Unauthorized Algorithm Modification Detected</description>
  </rule>

  <!-- Market Data API tracking - parent for DoS and MISP rules -->
  <rule id="100010" level="3">
    <decoded_as>hft_network_decoder</decoded_as>
    <match>GET /api/public/market-data</match>
    <description>Market Data API Request Tracking</description>
  </rule>

  <!-- HTTP Flood / DoS - 40+ requests from same IP in 30s -->
  <rule id="100004" level="14" frequency="40" timeframe="30">
    <if_matched_sid>100010</if_matched_sid>
    <same_source_ip />
    <description>CRITICAL: Potential Web HTTP Flood / DoS Attack Detected</description>
  </rule>

  <!-- MISP Threat Intel Match - dynamically synced from MISP
       IPs below are populated by sync_misp.sh. Do not edit manually. -->
  <rule id="100021" level="15">
    <if_sid>100010</if_sid>
${SRCIP_TAGS}
    <description>THREAT INTEL: Connection from MISP-flagged malicious IP \$(srcip)</description>
    <group>threat_intel,misp_match,</group>
  </rule>

  <!-- MISP IOC Detected - backend CEF event in app.log -->
  <rule id="100030" level="12">
    <decoded_as>hft_app_decoder</decoded_as>
    <match>MISP_IOC_Detected</match>
    <description>MISP Threat Intel: Malicious IP detected in HFT network traffic</description>
    <group>threat_intel,misp,</group>
  </rule>

  <!-- MISP CRITICAL severity - C2 or Ransomware IP specifically -->
  <rule id="100031" level="15">
    <if_sid>100030</if_sid>
    <match>severity=CRITICAL</match>
    <description>MISP CRITICAL: C2 or Ransomware IP active in HFT environment</description>
    <group>threat_intel,misp,apt,ransomware,</group>
  </rule>

  <!-- SOAR Auto-Block - new IP blocked for the first time -->
  <rule id="100032" level="13">
    <decoded_as>hft_app_decoder</decoded_as>
    <match>IP_Blocked</match>
    <description>SOAR Auto-Response: Malicious MISP IP blocked by automated containment</description>
    <group>soar,misp,block,</group>
  </rule>

  <!-- Blocked IP Repeat Attempt - persistent threat actor -->
  <rule id="100033" level="10">
    <decoded_as>hft_app_decoder</decoded_as>
    <match>IP_Block_Repeated</match>
    <description>SOAR: Previously blocked MISP IP attempted reconnection</description>
    <group>soar,misp,block_repeat,</group>
  </rule>

</group>
EOF

# Deploy to Wazuh container
echo "[*] Deploying rules to Wazuh container (${WAZUH_CTR})..."
docker cp /tmp/local_rules.xml ${WAZUH_CTR}:${RULES_FILE}

if [ $? -ne 0 ]; then
  echo "[!] Failed to copy rules. Is the container running?"
  echo "    Check: docker ps | grep wazuh"
  exit 1
fi

echo "[✓] Rules file deployed"

# Restart Wazuh to load new rules
echo "[*] Restarting Wazuh manager..."
docker exec ${WAZUH_CTR} /var/ossec/bin/wazuh-control restart

echo ""
echo "=================================================="
echo " [✓] Sync complete!"
echo "     Rules active: 100001, 100002, 100003, 100004,"
echo "                   100010, 100021 (${IP_COUNT} MISP IPs),"
echo "                   100030, 100031, 100032, 100033"
echo ""
echo " Verify in Wazuh UI:"
echo "   Security Events → filter: rule.groups: misp"
echo ""
echo " Or check via terminal:"
echo "   docker exec ${WAZUH_CTR} grep 'rule id' ${RULES_FILE}"
echo "=================================================="
